### ISSUE TITLE
Issue Out status: 256

### ISSUE THREAD

**Issue by guidopuccetti** [Gabaldonlab/perSVade#14] opened 2023-03-20 14:24 UTC
Hello! 
First of all, thanks for developing this tool!
I was going through it and decided to go for option 2 (docker). 
Nevertheless, I am unfamiliar with docker and have a hard time aligning the reads to my reference genome.

This below is the script that I am running in a loop for a small sample of 12 isolates.

my directory 

```
#!/bin/bash
filename="Trimmed_input.txt"
num_rows=$(wc -l < "$filename")

while read line
do
    col1=$(echo "$line" | cut -d' ' -f1)
    R2=$(echo $col1 | sed 's/1_trimmed/2_trimmed/')
    col2=$(echo "$line" | cut -d' ' -f2)
    echo "$col1"
	echo "$R2"

docker run -v /data4/guido/perSVade:/reference_genome_dir -v /data4/guido/perSVade:/output_dir -v /data4/guido/perSVade:/reads mikischikora/persvade:v1.02.6 python -u ./scripts/perSVade align_reads -r /reference_genome_dir/Zymoseptoria_tritici.MG2.dna.toplevel.mt+.fa -o /output_directory -f1 /reads/$col1 -f2 /reads/$R2 --fraction_available_mem 0.25
done < "$filename"
```
This is the error I am getting and I am not sure how to fix it. 

```
Traceback (most recent call last):
  File "./scripts/align_reads", line 146, in <module>
    fun.run_bwa_mem(opt.fastq1, opt.fastq2, opt.ref, opt.outdir, bamfile, sorted_bam, index_bam, sample_name, threads=opt.threads, replace=opt.replace, tmpdir_writingFiles=opt.tmpdir, MarkDuplicates=bwa_mem_MarkDuplicates)
  File "./scripts/sv_functions.py", line 1321, in run_bwa_mem
    cmd_bwa = '%s mem -R "@RG\\tID:%s\\tSM:%s" -t %i %s %s %s > %s 2>%s'%(bwa, name_sample, name_sample, threads, ref, fastq1, fastq2, samfile_tmp, bwa_mem_stderr); run_cmd(cmd_bwa)
  File "./scripts/sv_functions.py", line 691, in run_cmd
    if out_stat!=0: raise ValueError("\n%s\n did not finish correctly. Out status: %i"%(cmd_to_run, out_stat))
ValueError: 
source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env > /dev/null 2>&1 && /opt/conda/envs/perSVade_env/bin/bwa mem -R "@RG\tID:SAMPLE\tSM:SAMPLE" -t 16 /output_directory/reference_genome_dir/reference_genome.fasta /reads/D01_FDSW202500540-1r_HCHN5DSXY_L2_1_trimmed.fq.gz /reads/D01_FDSW202500540-1r_HCHN5DSXY_L2_2_trimmed.fq.gz > /output_directory/aligned_reads.sam.tmp 2>/output_directory/aligned_reads.sam.tmp.stderr
 did not finish correctly. Out status: 256

ERROR!!! Out status: 256
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['python', '-u', './scripts/perSVade', 'align_reads', '-r', '/reference_genome_dir/Zymoseptoria_tritici.MG2.dna.toplevel.mt+.fa', '-o', '/output_directory', '-f1', '/reads/D01_FDSW202500540-1r_HCHN5DSXY_L2_1_trimmed.fq.gz', '-f2', '/reads/D01_FDSW202500540-1r_HCHN5DSXY_L2_2_trimmed.fq.gz', '--fraction_available_mem', '0.25']' command failed.  (See above for error)
```
Any suggestion would be really appreciated! Thanks!

**Comment by MikiSchikora** [comment] 2023-03-21 08:31
Hi,

It seems that the mapping is failing. To check the source of the error I'd need to see the <output_dir>/aligned_reads.sam.tmp.stderr file. The problem I see is that you are writing the results into /output_directory inside the docker container, but if I think that this directory will not exist in the host machine (your computer). So when the docker run ends the /output_directory  (and thus aligned_reads.sam.tmp.stderr) will not exist. 

In docker, if you want that the files generated are kept in the host machine you need to specify mounting points (with -v). In your command, I see that you specified `-v /data4/guido/perSVade:/output_dir`. Is it possible that you want the output directory to be `/data4/guido/perSVade`? If so you may specify `-v /data4/guido/perSVade:/output_directory`. Can you try this and, if the error persists, show me here the content of aligned_reads.sam.tmp.stderr ?

In general, I find that singularity is better from the perspective of mounting points, as it already mounts several directories by default.

Best,

Miquel Àngel Schikora
Barcelona Supercomputing Center

**Comment by MikiSchikora** [comment] 2023-03-28 13:23
Hi,

Could you solve this? If so I'd close this issue.

Best,

Miquel Àngel Schikora
Barcelona Supercomputing Center

**Comment by guidopuccetti** [comment] 2023-03-29 14:44
Hi Miquel, 

Thanks, your suggestion solved the issue, but I run into a new problem that seems to be related to bwa.

When I run the following script to align the reads

docker run -v /data4/guido/perSVade:/reference_genome_dir -v /data4/guido/perSVade:/output_directory -v /data4/guido/perSVade:/reads mikischikora/persvade:v1.02.6 python -u ./scripts/perSVade align_reads -r /reference_genome_dir/Zymoseptoria_tritici.MG2.dna.toplevel.mt+.fa -o /output_directory -f1 /reads/fine_D02_FDSW202500541-1r_HCHN5DSXY_L2_1_trimmed.fq.gz -f2 /reads/fine_D02_FDSW202500541-1r_HCHN5DSXY_L2_2_trimmed.fq.gz --fraction_available_mem 0.25

I got the following issue in aligned_reads.sam.tmp.stderr

```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 1067056 sequences (160000114 bp)...
[M::process] read 1067026 sequences (160000267 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (66, 13865, 84, 49)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (1488, 4509, 6913)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 17763)
[M::mem_pestat] mean and std.dev: (4286.14, 2866.45)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 23188)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (294, 341, 391)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (100, 585)
[M::mem_pestat] mean and std.dev: (342.14, 73.53)
[M::mem_pestat] low and high boundaries for proper pairs: (3, 682)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (2917, 4352, 6695)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 14251)
[M::mem_pestat] mean and std.dev: (4758.30, 2466.50)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 18029)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (1466, 3589, 6906)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 17786)
[M::mem_pestat] mean and std.dev: (4287.02, 2856.11)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 23226)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[mem_sam_pe] paired reads have different names: "A00821:430:HCHN5DSXY:2:1101:19153:5415", "A00821:430:HCHN5DSXY:2:1101:19768:5415"
```
My reads are already paired and sorted. Nevertheless, I checked online and I saw that this is a common issue with bwa and that with fastq_pair I could have paired and sorted the fastq files. I did it but I got the same error. 

Should I start use your ./scripts/perSVade trim_reads_and_QC -f1 reads1.fastq.gz -f2 reads2.fastq.gz -o output/trimmed_reads rather than any different tool for trimming and pairing?

Sorry, if it took so long to reply, I have been really busy lately and I could not really work on this project!
Best,
Guido

**Comment by MikiSchikora** [comment] 2023-03-29 15:53
Hi,

No worries on the late reply. I am not aware about this issue, but it looks like an unexpected behavior from the trimming software as you say. As far as I understand, there is this pair of reads ("A00821:430:HCHN5DSXY:2:1101:19153:5415", "A00821:430:HCHN5DSXY:2:1101:19768:5415") that do have different names but are in the same line, which is something that bwa will not allow. The input reads should have proper pairing, with equal names in both FWD and RV reads.

You can try trimming the raw reads with trim_reads_and_QC, or use trimmomatic with any custom configuration, which should return properly paired reads.

I hope this helps,

Best,

Miquel Àngel Schikora
Barcelona Supercomputing Center

**Comment by MikiSchikora** [comment] 2023-04-13 14:39
Good afternoon,

Could you solve the issues?

Best,

Miquel Àngel Schikora
Barcelona Supercomputing Center

**Comment by guidopuccetti** [comment] 2023-04-19 16:15
Yes thanks!!

**Closed as completed** 2023-04-21 13:51 UTC
